##Part 2

1.Check if the sentence is Grammatically correct: Please use any pre-trained model or use text from open datasets. Once done, please evaluate the English Grammar in the text column of the dataset.

In [30]:
!pip install language-tool-python

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: language-tool-python in /usr/local/lib/python3.7/dist-packages (2.7.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from language-tool-python) (4.64.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from language-tool-python) (2.23.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->language-tool-python) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->language-tool-python) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->language-tool-python) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->language-tool-python) (2022.6.15)

In [31]:
import numpy as np
import pandas as pd
import language_tool_python
tool = language_tool_python.LanguageTool('en-US')  # language English-US
from textblob import TextBlob

In [50]:
data=pd.read_csv('/content/review_data.csv',nrows=1000)
pd.set_option("display.max_column", None)
display(data.head())

,text,star,app_id,reviewDate
0,Anathi Khanyile,5,com.fingersoft.hillclimb,18/03/21
1,Tony bahut funny hai Hill climbing racing my f...,5,com.fingersoft.hillclimb,18/03/21
2,Teturwu,1,com.fingersoft.hillclimb,18/03/21
3,Hoooooooooooyaaaaaaaaa what a game hoooooooooo...,5,com.fingersoft.hillclimb,18/03/21
4,This game is nice,5,com.fingersoft.hillclimb,18/03/21

In [51]:
data.shape

(1000, 4)

In [52]:
# check missing values
data.isnull().sum()

text          0
star          0
app_id        0
reviewDate    0
dtype: int64

In [53]:
df=data[['text']]

In [54]:
df.head()

                                                text
0                                    Anathi Khanyile
1  Tony bahut funny hai Hill climbing racing my f...
2                                            Teturwu
3  Hoooooooooooyaaaaaaaaa what a game hoooooooooo...
4                                  This game is nice

In [55]:
#check the sentance is correct or not
try:
    df = df.assign(Grammatical_Status = ['Incorrect' if len(tool.check(rows))>0 else 'Correct' for rows in df.text])
except Exception as e:
    print('Error: ', e)

In [56]:
df.head()

                                                text Grammatical_Status
0                                    Anathi Khanyile          Incorrect
1  Tony bahut funny hai Hill climbing racing my f...          Incorrect
2                                            Teturwu          Incorrect
3  Hoooooooooooyaaaaaaaaa what a game hoooooooooo...          Incorrect
4                                  This game is nice            Correct

In [57]:
#correct the sentance
try:
    df = df.assign(Corrected = [tool.correct(rows) for rows in df.text])
except Exception as e:
    print('Error: ', e)

In [58]:
df.head()

,text,Grammatical_Status,Corrected
0,Anathi Khanyile,Incorrect,Anti Handle
1,Tony bahut funny hai Hill climbing racing my f...,Incorrect,Tony Beirut funny HAI Hill climbing racing my ...
2,Teturwu,Incorrect,Return
3,Hoooooooooooyaaaaaaaaa what a game hoooooooooo...,Incorrect,Hoooooooooooyaaaaaaaaa what a game hoooooooooo...
4,This game is nice,Correct,This game is nice